version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGODB_DATABASE: devtest      
      MONGODB_HOSTNAME: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    command: /bin/bash -c 'mongod'
volumes:
  mongodb_data_container:
  
  # sudo docker container exec -it 5acd987e400e /bin/sh
